name: Auto Generate Solar Activity Video

on:
  schedule:
    - cron: '00 0 * * *'  # Exécution automatique chaque jour à 01h00 UTC
  workflow_dispatch:        # Lancement manuel depuis l'onglet Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily solar activity script
        run: python autovideo_daily.py

      - name: Upload final videos as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: solar_activity_videos
          path: solar_activity/

      - name: Commit generated videos (if size is small enough)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add solar_activity/*.mp4 || true
          git diff --cached --quiet || (git commit -m "add solar activity video $(date +'%d:%m:%Y')" && git push)
